format_version: 10
pipelines:
  "prm-gp-registration-mi-reporting":
    group: gp-registrations-mi
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - upload:
          clean_workspace: true
          jobs:
            deploy:
              tasks:
                # upload-dashboards-and-reports-datasets
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh upload_data
      - lambda_deploy:
          clean_workspace: true
          jobs:
            deploy:
              tasks:
                # build lambda and deploy
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh build_and_deploy_splunk_uploader_lambda
