format_version: 10
pipelines:
  "prm-gp-registration-mi-reporting":
    group: gp-registrations-mi
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - deploy:
          clean_workspace: true          
          jobs:
            deploy:
              tasks:               
                # upload-dashboards-and-reports-datasets
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh upload_data
                # build lambda and deploy
                # - exec:
                #     command: /bin/bash
                #     arguments:
                #       - -c
                #       - ./tasks.sh build_and_deploy_splunk_uploader_lambda
                # Invoke lambda to dashboards and reports to Splunk
                # - exec:
                #     command: /bin/bash
                #     arguments:
                #       - -c
                #       - ./tasks.sh run_splunk_uploader_lambda