format_version: 10
pipelines:
  "prm-gp-registration-mi-reporting":
    group: gp-registrations-mi
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - deploy:
          clean_workspace: true          
          jobs:
            deploy:
              tasks:
                # build and run docker container
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh build_docker_image
                # upload-dashboards-and-reports-datasets
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh upload_data
                # - exec:
                #     command: /bin/bash
                #     arguments:
                #       - -c
                #       - ./scripts/build-and-publish.sh